// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: file_partition.proto

package messages

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FilePartitionClient is the client API for FilePartition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilePartitionClient interface {
	PartitionFile(ctx context.Context, in *FilePartitionRequest, opts ...grpc.CallOption) (*FilePartitionResponse, error)
}

type filePartitionClient struct {
	cc grpc.ClientConnInterface
}

func NewFilePartitionClient(cc grpc.ClientConnInterface) FilePartitionClient {
	return &filePartitionClient{cc}
}

func (c *filePartitionClient) PartitionFile(ctx context.Context, in *FilePartitionRequest, opts ...grpc.CallOption) (*FilePartitionResponse, error) {
	out := new(FilePartitionResponse)
	err := c.cc.Invoke(ctx, "/messages.FilePartition/PartitionFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilePartitionServer is the server API for FilePartition service.
// All implementations must embed UnimplementedFilePartitionServer
// for forward compatibility
type FilePartitionServer interface {
	PartitionFile(context.Context, *FilePartitionRequest) (*FilePartitionResponse, error)
	mustEmbedUnimplementedFilePartitionServer()
}

// UnimplementedFilePartitionServer must be embedded to have forward compatible implementations.
type UnimplementedFilePartitionServer struct {
}

func (UnimplementedFilePartitionServer) PartitionFile(context.Context, *FilePartitionRequest) (*FilePartitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PartitionFile not implemented")
}
func (UnimplementedFilePartitionServer) mustEmbedUnimplementedFilePartitionServer() {}

// UnsafeFilePartitionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilePartitionServer will
// result in compilation errors.
type UnsafeFilePartitionServer interface {
	mustEmbedUnimplementedFilePartitionServer()
}

func RegisterFilePartitionServer(s grpc.ServiceRegistrar, srv FilePartitionServer) {
	s.RegisterService(&FilePartition_ServiceDesc, srv)
}

func _FilePartition_PartitionFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilePartitionServer).PartitionFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.FilePartition/PartitionFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilePartitionServer).PartitionFile(ctx, req.(*FilePartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilePartition_ServiceDesc is the grpc.ServiceDesc for FilePartition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilePartition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messages.FilePartition",
	HandlerType: (*FilePartitionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PartitionFile",
			Handler:    _FilePartition_PartitionFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file_partition.proto",
}
