# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chunk_storage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63hunk_storage.proto\x12\rchunk_storage\";\n\x11StoreChunkRequest\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\x12\x12\n\nchunk_hash\x18\x02 \x01(\t\"$\n\x12StoreChunkResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2a\n\x0c\x43hunkStorage\x12Q\n\nStoreChunk\x12 .chunk_storage.StoreChunkRequest\x1a!.chunk_storage.StoreChunkResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chunk_storage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STORECHUNKREQUEST._serialized_start=38
  _STORECHUNKREQUEST._serialized_end=97
  _STORECHUNKRESPONSE._serialized_start=99
  _STORECHUNKRESPONSE._serialized_end=135
  _CHUNKSTORAGE._serialized_start=137
  _CHUNKSTORAGE._serialized_end=234
# @@protoc_insertion_point(module_scope)
