# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import file_splitter_pb2 as file__splitter__pb2


class FileSplitterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SplitFile = channel.unary_unary(
                '/file_splitter.FileSplitter/SplitFile',
                request_serializer=file__splitter__pb2.FileRequest.SerializeToString,
                response_deserializer=file__splitter__pb2.FileResponse.FromString,
                )


class FileSplitterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SplitFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileSplitterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SplitFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SplitFile,
                    request_deserializer=file__splitter__pb2.FileRequest.FromString,
                    response_serializer=file__splitter__pb2.FileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'file_splitter.FileSplitter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileSplitter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SplitFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file_splitter.FileSplitter/SplitFile',
            file__splitter__pb2.FileRequest.SerializeToString,
            file__splitter__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
