# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_splitter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_splitter.proto\x12\rfile_splitter\"\x1e\n\x0b\x46ileRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\x1f\n\x0c\x46ileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2T\n\x0c\x46ileSplitter\x12\x44\n\tSplitFile\x12\x1a.file_splitter.FileRequest\x1a\x1b.file_splitter.FileResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_splitter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILEREQUEST._serialized_start=38
  _FILEREQUEST._serialized_end=68
  _FILERESPONSE._serialized_start=70
  _FILERESPONSE._serialized_end=101
  _FILESPLITTER._serialized_start=103
  _FILESPLITTER._serialized_end=187
# @@protoc_insertion_point(module_scope)
